#!/bin/sh
apt --yes install /tmp/eagine-core-dev.deb
mkdir -p /tmp/eagine/_build
cd /tmp/eagine/_build
cmake /tmp/eagine
cmake --build /tmp/eagine/_build
for e in /tmp/eagine/_build/example/eagine-*
do ${e} --use-null-log
done
