#!/bin/bash -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
#
this_dir="$(realpath $(dirname ${0}))"
work_dir="$(mktemp -d)"
architecture=$(docker info | sed -n 's/^\s*Architecture:\s*\(\w\+\)\s*$/\1/p')

function cleanup() {
	rm -rf "${work_dir}"
}

trap cleanup EXIT

mkdir -p "${work_dir}/cfg"
cp "${this_dir}/Dockerfile" "${work_dir}/"
cp "${this_dir}/cfg/eagilog.conf" "${work_dir}/cfg/"
cp "${this_dir}/cfg/index.html" "${work_dir}/cfg/"

if [[ -f "${this_dir}/eagilog_frontend.crt" ]]
then cp "${this_dir}/eagilog_frontend.crt" "${work_dir}/eagilog_frontend.crt"
else openssl req \
	-new -x509 \
	-subj "/CN=eagilog/O=OGLplus.org/OU=EAGine" \
	-days 365 \
	-key "${this_dir}/../_secrets/eagilog_frontend.pkey" \
	-sha256 \
	-out "${work_dir}/eagilog_frontend.crt"
fi

if [[ -f "${this_dir}/eagilog_grafana.crt" ]]
then cp "${this_dir}/eagilog_grafana.crt" "${work_dir}/eagilog_grafana.crt"
else openssl req \
	-new -x509 \
	-subj "/CN=grafana.eagilog/O=OGLplus.org/OU=EAGine" \
	-days 365 \
	-key "${this_dir}/../_secrets/eagilog_frontend.pkey" \
	-sha256 \
	-out "${work_dir}/eagilog_grafana.crt"
fi

if [[ -f "${this_dir}/eagilog_web.crt" ]]
then cp "${this_dir}/eagilog_web.crt" "${work_dir}/eagilog_web.crt"
else openssl req \
	-new -x509 \
	-subj "/CN=web.eagilog/O=OGLplus.org/OU=EAGine" \
	-days 365 \
	-key "${this_dir}/../_secrets/eagilog_frontend.pkey" \
	-sha256 \
	-out "${work_dir}/eagilog_web.crt"
fi

docker build "${work_dir}" \
	--tag eagine/eagine:eagilog_frontend-${architecture:-unknown}

