#!/bin/bash -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
# https://www.boost.org/LICENSE_1_0.txt
#
source "$(dirname ${0})/build"
docker tag eagine/eagine:eagilog_frontend-${architecture:-unknown} eagine/eagine:eagilog_frontend
docker push eagine/eagine:eagilog_frontend
docker service update --force eagilog_eagilog_frontend --image eagine/eagine:eagilog_frontend
