#!/bin/bash -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
#
source "$(dirname ${BASH_SOURCE[0]})/../../../common.sh"
this_dir="$(realpath $(dirname ${0}))"
repo_dir="$(realpath $(dirname ${0})/../../../..)"
work_dir="$(mktemp -d)"

function cleanup() {
	rm -rf "${work_dir}"
}

trap cleanup EXIT

mkdir -p "${work_dir}/user/eagilog"
cp  "${repo_dir}/source/app/log_server/postgresql/eagilog.sql"\
    "${work_dir}/user/eagilog/eagilog.sql"
mkdir -p "${work_dir}/bin"
cc -no-pie -static -o "${work_dir}/bin/eagine-getpwd" "${this_dir}/bin/getpwd.c"
cp "${this_dir}/bin/init.sh" "${work_dir}/bin"
cp "${this_dir}/Dockerfile" "${work_dir}/"

docker build "${work_dir}" \
	--tag ${EAGINE_DOCKER_REGISTRY}/eagine:eagilog_postgres \

docker tag \
	${EAGINE_DOCKER_REGISTRY}/eagine:eagilog_postgres \
	eagine/eagine:eagilog_postgres

