#!/bin/bash -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
#
function gen_passwd() {
	head -c 64 /dev/urandom | base64 -w 0 - | cut -b-64 | tr '/:@' '-_+' | tr -d '\n'
}

function has_docker_secret() {
	docker secret ls --format "{{.Name}}" | grep -q "${1}"
}

function ensure_passwd() {
	has_docker_secret "${1}" || gen_passwd | docker secret create "${1}" -
}

function ensure_ssl_key() {
	has_docker_secret "${1}" || openssl genrsa 4096 | docker secret create "${1}" -
}

ensure_passwd "postgres_postgres.passwd"
ensure_passwd "eagilog_postgres.passwd"
ensure_passwd "backup_postgres.passwd"
ensure_passwd "admin_influxdb.passwd"
ensure_passwd "admin_grafana.passwd"
ensure_passwd "eagilog_influxdb.token"
ensure_ssl_key "eagilog_frontend.pkey"

