#!/bin/bash -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
# https://www.boost.org/LICENSE_1_0.txt
#
work_dir="$(mktemp -d)"

function cleanup() {
	rm -rf "${work_dir}"
}

trap cleanup EXIT

function gen_passwd() {
	head -c 64 /dev/urandom | base64 -w 0 - | cut -b-64 | tr '/:@' '-_+' | tr -d '\n'
}

function has_docker_secret() {
	docker secret ls --format "{{.Name}}" | grep -q "${1}"
}

function ensure_passwd() {
	has_docker_secret "${1}" || gen_passwd | docker secret create "${1}" -
}

function ensure_ssl_key() {
	if ! has_docker_secret "${1}"
	then
		if ! [[ -f "${work_dir}/${1}" ]]
		then openssl genrsa -out "${work_dir}/${1}" 4096
		fi
		docker secret create "${1}" "${work_dir}/${1}"
	fi
}

ensure_passwd "postgres_postgres.passwd"
ensure_passwd "eagilog_postgres.passwd"
ensure_passwd "backup_postgres.passwd"
ensure_passwd "admin_influxdb.passwd"
ensure_passwd "admin_grafana.passwd"
ensure_passwd "eagilog_influxdb.token"
ensure_ssl_key "eagilog_frontend.pkey"

for fe in influxdb grafana web
do
	if ! has_docker_secret eagilog_${fe}.crt
	then 
		openssl req \
			-new \
			-subj "/CN=${fe}.eagilog/O=OGLplus.org/OU=EAGine" \
			-addext "subjectAltName = DNS:${fe}.eagilog"  \
			-key "${work_dir}/eagilog_frontend.pkey" \
			-sha512 \
			-out eagilog_${fe}.csr &&\
		openssl req \
			-new -x509 \
			-subj "/CN=${fe}.eagilog/O=OGLplus.org/OU=EAGine" \
			-addext "subjectAltName = DNS:${fe}.eagilog"  \
			-days 365 \
			-key "${work_dir}/eagilog_frontend.pkey" \
			-sha512 |\
		docker secret create eagilog_${fe}.crt - &&\
		echo openssl x509 \
			-req \
			-in eagilog_${fe}.csr \
			-CA /path/to/ca.crt \
			-copy_extensions copy \
			-set_serial X \
			-sha512 \
			-out eagilog_${fe}.crt
	fi
done

