#!/bin/bash -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
#
# usage: make_multiplatform x86_64 aarch64 ...
#
for container in influxdb postgres grafana server web frontend
do "$(dirname ${0})/${container}/make_multiplatform" "${@}"
done
