#!/bin/bash -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
#
source "$(dirname ${BASH_SOURCE[0]})/../../common.sh"
this_dir="$(realpath $(dirname ${0}))"
cfg_dir="${1:-${this_dir}}"

if [[ -d "${cfg_dir}/_secrets" ]]
then pwd_dir="${cfg_dir}/_secrets"
elif [[ -d "${cfg_dir}/secrets" ]]
then pwd_dir="${cfg_dir}/secrets"
fi

cat << COMPOSE
version: "3.6"
services:
    eagilog_influxdb:
        image: ${EAGINE_DOCKER_REGISTRY}/eagine:eagilog_influxdb
        restart: always
        networks:
          - eagilog
        ports:
          - "8086:8086"
        environment:
          - INFLUXDB_DB=db0
          - INFLUXDB_ADMIN_USER=eagine
          - INFLUXDB_ADMIN_PASSWORD=$(<${pwd_dir}/admin_influxdb.passwd)
        volumes:
          - influxdb-etc-storage:/etc/influxdb2
          - influxdb-var-storage:/var/lib/influxdb2
    eagilog_postgres:
        image: ${EAGINE_DOCKER_REGISTRY}/eagine:eagilog_postgres
        restart: always
        networks:
          - eagilog
        ports:
          - "5432:5432"
        secrets:
          - postgres_postgres.passwd
          - eagilog_postgres.passwd
          - backup_postgres.passwd
        volumes:
          - postgres-storage:/var/lib/postgresql
    eagilog_grafana:
        image: ${EAGINE_DOCKER_REGISTRY}/eagine:eagilog_grafana
        restart: always
        networks:
          - eagilog
        ports:
          - "3000:3000"
        volumes:
          - grafana-storage:/var/lib/grafana
        environment:
          - GF_SECURITY_ADMIN_USER=eagine
          - GF_SECURITY_ADMIN_PASSWORD=$(<${pwd_dir}/admin_grafana.passwd)
        depends_on:
          - eagilog_influxdb
    eagilog_server:
        image: ${EAGINE_DOCKER_REGISTRY}/eagine:eagilog_server
        restart: always
        networks:
          - eagilog
        ports:
          - "34915:34915"
          - "34917:34917"
        secrets:
          - eagilog_postgres.passwd
          - eagilog_influxdb.token
        depends_on:
          - eagilog_influxdb
          - eagilog_postgres
    eagilog_web:
        image: ${EAGINE_DOCKER_REGISTRY}/eagine:eagilog_web
        restart: always
        networks:
          - eagilog
        ports:
          - "34913:34913"
        environment:
          - EAGILOG_WEB_PORT=34913
        secrets:
          - eagilog_postgres.passwd
        depends_on:
          - eagilog_influxdb
    eagilog_frontend:
        image: ${EAGINE_DOCKER_REGISTRY}/eagine:eagilog_frontend
        restart: always
        networks:
          - eagilog
        ports:
          - "8080:80"
          - "8443:443"
        secrets:
          - eagilog_influxdb.crt
          - eagilog_grafana.crt
          - eagilog_web.crt
          - eagilog_frontend.pkey
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
        depends_on:
          - eagilog_grafana
          - eagilog_web

networks:
    eagilog:

secrets:
    postgres_postgres.passwd:
        file: ${pwd_dir}/postgres_postgres.passwd
    eagilog_postgres.passwd:
        file: ${pwd_dir}/eagilog_postgres.passwd
    backup_postgres.passwd:
        file: ${pwd_dir}/backup_postgres.passwd
    eagilog_influxdb.token:
        file: ${pwd_dir}/eagilog_influxdb.token
    eagilog_frontend.pkey:
        file: ${pwd_dir}/eagilog_frontend.pkey

volumes:
    influxdb-etc-storage:
    influxdb-var-storage:
    postgres-storage:
    grafana-storage:
COMPOSE

