#!/bin/bash -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
# https://www.boost.org/LICENSE_1_0.txt
#
architectures=("${@}")
for arch in "${architectures[@]}"
do docker pull eagine/eagine:eagilog_grafana-${arch}
done

amend_args=(${architectures[@]/#/--amend eagine/eagine:eagilog_grafana-})
docker manifest create eagine/eagine:eagilog_grafana "${amend_args[@]}"

docker manifest push eagine/eagine:eagilog_grafana
