#!/bin/bash -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
#
this_dir="$(realpath $(dirname ${0}))"

docker build "${this_dir}" \
	--network host \
	--tag eagine/eagine:eagilog_server

