#!/bin/sh -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
# https://www.boost.org/LICENSE_1_0.txt
#
if getent passwd eagine > /dev/null
then
	if [ "x${1}x" = "xremovex" ]
	then
		deluser --quiet --remove-home --remove-all-files eagine 2> /dev/null
		if getent group eagine > /dev/null
		then delgroup eagine
		fi
	fi
fi

