#!/bin/sh -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
# https://www.boost.org/LICENSE_1_0.txt
#
chown -R eagine:eagine "/etc/eagine"
chown -R eagine:eagine "/var/lib/eagine"
chown -R eagine:eagine "/var/run/eagine"

