#!/bin/bash -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
#
this_dir="$(realpath $(dirname ${0}))"

function gen_passwd() {
	head -c 64 /dev/urandom | base64 -w 0 - | cut -b-64 | tr -d '\n'
}

function ensure_passwd() {
	[[ -f "${1}" ]] || gen_passwd > "${1}"
	chmod 600 "${1}"
}

mkdir -p "${this_dir}/_secrets/"
ensure_passwd "${this_dir}/_secrets/postgres_pg.passwd"
ensure_passwd "${this_dir}/_secrets/eagilog_pg.passwd"
ensure_passwd "${this_dir}/_secrets/backup_pg.passwd"

"$(dirname ${0})/database/build"
"$(dirname ${0})/forwarder/build"
