version: "3.6"
services:
    log_psql_database:
        image: eagine:log_psql_database
        restart: always
        networks:
          - eagilog
        ports:
          - 5432:5432
        secrets:
          - postgres_pg.passwd
          - eagilog_pg.passwd
          - backup_pg.passwd
    log_psql_forwarder:
        image: eagine:log_psql_forwarder
        restart: always
        networks:
          - eagilog
        ports:
          - 34917:34917
        secrets:
          - eagilog_pg.passwd
        depends_on:
          - log_psql_database

networks:
    eagilog:
        internal: true

secrets:
    postgres_pg.passwd:
        file: ./_secrets/postgres_pg.passwd
    eagilog_pg.passwd:
        file: ./_secrets/eagilog_pg.passwd
    backup_pg.passwd:
        file: ./_secrets/backup_pg.passwd
