#!/bin/bash -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
#
this_dir="$(realpath $(dirname ${0}))"
repo_dir="$(realpath $(dirname ${0})/../../../..)"
work_dir="$(mktemp -d)"

function cleanup() {
	rm -rf "${work_dir}"
}

trap cleanup EXIT

mkdir -p "${work_dir}/_secrets"
cp "${this_dir}/../_secrets/"*_pg.passwd "${work_dir}/_secrets"
mkdir -p "${work_dir}/user/eagilog"
cp "${repo_dir}/source/app/xml_logs-psql.sql" "${work_dir}/user/eagilog/eagilog.sql"
mkdir -p "${work_dir}/bin"
cp "${this_dir}/bin/init.sh" "${work_dir}/bin"
chmod a+x "${work_dir}/bin"
cp "${this_dir}/Dockerfile" "${work_dir}/"

cat > "${work_dir}/docker-compose.yml" << COMPOSE
version: "3.6"
services:
    log_psql_db:
        build: .
        image: ${EAGINE_DOCKER_REGISTRY_HOST:-localhost}:${EAGINE_DOCKER_REGISTRY_PORT:-5000}/eagine:log_psql_db
COMPOSE

pushd "${work_dir}"
docker-compose build log_psql_db

docker tag \
	${EAGINE_DOCKER_REGISTRY_HOST:-localhost}:${EAGINE_DOCKER_REGISTRY_PORT:-5000}/eagine:log_psql_db \
	eagine:log_psql_db

