#!/bin/bash -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
#
source "$(dirname ${BASH_SOURCE[0]})/../../common.sh"
this_dir="$(realpath $(dirname ${0}))"
# ------------------------------------------------------------------------------
# docker compose
# ------------------------------------------------------------------------------
cfg_dir="${HOME}/.config/eagine/eagilog/psql"
mkdir -p "${cfg_dir}/secrets"
rm -f "${cfg_dir}/secrets/"*

cp "${this_dir}/_secrets/"* "${cfg_dir}/secrets/"
chmod 400 "${cfg_dir}/secrets/"*

"${this_dir}/make_compose" > "${cfg_dir}/docker-compose.yml"
# ------------------------------------------------------------------------------
# executables
# ------------------------------------------------------------------------------
bin_dir="${HOME}/.local/bin"
mkdir -p "${bin_dir}"

rm -f "${bin_dir}/eaglog-server-start"
cat > "${bin_dir}/eaglog-server-start" << START
#!/bin/bash -e
pushd "${cfg_dir}"
docker-compose up --detach
START
chmod 555 "${bin_dir}/eaglog-server-start"

rm -f "${bin_dir}/eaglog-server-stop"
cat > "${bin_dir}/eaglog-server-stop" << STOP
#!/bin/bash -e
pushd "${cfg_dir}"
docker-compose down
STOP
chmod 555 "${bin_dir}/eaglog-server-stop"
# ------------------------------------------------------------------------------
# systemd service
# ------------------------------------------------------------------------------
sdc_dir="${HOME}/.config/systemd/user"
mkdir -p "${sdc_dir}"
rm -f "${sdc_dir}/eagilog-server.service"
cat > "${sdc_dir}/eagilog-server.service" << SERVICE
[Unit]
Description=eagine logging server server.

[Service]
Type=oneshot
WorkingDirectory=${cfg_dir}
RemainAfterExit=yes
ExecStart=/bin/bash ${bin_dir}/eaglog-server-start
ExecStop=/bin/bash  ${bin_dir}/eaglog-server-stop

[Install]
WantedBy=default.target
SERVICE

systemctl --user daemon-reload
systemctl --user enable eagilog-psql
# ------------------------------------------------------------------------------
