#!/bin/bash -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
#
source "$(dirname ${BASH_SOURCE[0]})/../../common.sh"
this_dir="$(realpath $(dirname ${0}))"
cfg_dir="${1:-${this_dir}}"

if [[ -d "${cfg_dir}/_secrets" ]]
then pwd_dir="${cfg_dir}/_secrets"
elif [[ -d "${cfg_dir}/secrets" ]]
then pwd_dir="${cfg_dir}/secrets"
fi

cat << COMPOSE
version: "3.6"
services:
    eagilog_influxdb:
        image: ${EAGINE_DOCKER_REGISTRY}/eagine:eagilog_influxdb
        restart: always
        networks:
          - eagilog
        ports:
          - "8086:8086"
        environment:
         - INFLUXDB_DB=db0
         - INFLUXDB_ADMIN_USER=eagine
         - INFLUXDB_ADMIN_PASSWORD=$(<${pwd_dir}/admin_influxdb.passwd)
    eagilog_postgres:
        image: ${EAGINE_DOCKER_REGISTRY}/eagine:eagilog_postgres
        restart: always
        networks:
          - eagilog
        ports:
          - "5432:5432"
        secrets:
          - postgres_pg.passwd
          - eagilog_pg.passwd
          - backup_pg.passwd
    eagilog_server:
        image: ${EAGINE_DOCKER_REGISTRY}/eagine:eagilog_server
        restart: always
        networks:
          - eagilog
        ports:
          - "34915:34915"
          - "34917:34917"
        secrets:
          - eagilog_pg.passwd
        depends_on:
          - eagilog_influxdb
          - eagilog_postgres

networks:
    eagilog:

secrets:
    postgres_pg.passwd:
        file: ${pwd_dir}/postgres_pg.passwd
    eagilog_pg.passwd:
        file: ${pwd_dir}/eagilog_pg.passwd
    backup_pg.passwd:
        file: ${pwd_dir}/backup_pg.passwd
COMPOSE

