#!/bin/bash -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
#
"$(dirname ${0})/influxdb/push"
"$(dirname ${0})/postgres/push"
"$(dirname ${0})/grafana/push"
"$(dirname ${0})/server/push"
