#!/bin/bash -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
#
source "$(dirname ${BASH_SOURCE[0]})/../../common.sh"
this_dir="$(realpath $(dirname ${0}))"
temp_dir="$(mktemp -d)"

function cleanup() {
	rm -rf "${temp_dir}"
}

trap cleanup EXIT

work_dir="${temp_dir}/eagine"

mkdir -p "${work_dir}/_secrets/"
cp "${this_dir}/_secrets/"* "${work_dir}/_secrets/"
chmod 400 "${work_dir}/_secrets/"*

"${this_dir}/make_compose" > "${work_dir}/docker-compose.yml"

pushd "${work_dir}"
docker-compose up
