#!/bin/bash -e
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
# https://www.boost.org/LICENSE_1_0.txt
#
this_dir="$(realpath $(dirname ${0}))"
repo_dir="$(realpath $(dirname ${0})/../../../..)"
work_dir="$(mktemp -d)"
architecture=$(docker info | sed -n 's/^\s*Architecture:\s*\(\w\+\)\s*$/\1/p')

function cleanup() {
	rm -rf "${work_dir}"
}

trap cleanup EXIT

mkdir -p "${work_dir}/user/eagilog"
if [[ -f "/usr/share/eagine/eagilog.sql" ]]
then cp "/usr/share/eagine/eagilog.sql" "${work_dir}/user/eagilog/eagilog.sql"
else cp "${repo_dir}/source/app/log_server/postgresql/eagilog.sql"\
    	"${work_dir}/user/eagilog/eagilog.sql"
fi
mkdir -p "${work_dir}/bin"
cc -no-pie -static -o "${work_dir}/bin/eagine-getpwd" "${this_dir}/bin/getpwd.c"
cp "${this_dir}/bin/init.sh" "${work_dir}/bin"
cp "${this_dir}/Dockerfile" "${work_dir}/"

docker build "${work_dir}" \
	--tag eagine/eagine:eagilog_postgres-${architecture:-unknown}

